- name: Install dependency packages 
  package:
    name: "{{item}}"
    state: present 
  loop: ["apr-util-devel", "gcc", "pcre-devel", "libxml2-devel", "mariadb"]

- name: Download Apache 
  unarchive:
    src: https://www-eu.apache.org/dist//httpd/httpd-2.4.39.tar.gz
    dest: /root
    remote_src: yes

- name: Compile Apache 
  shell: cd /root/httpd-2.4.39 && ./configure && make clean && make && make install 

- name: Create two hard links
  file:
    src: /usr/local/apache2/bin/apachectl
    dest: /etc/init.d/httpd
    state: link

- name: Reload Systemctl Daemon 
  shell: systemctl daemon-reload 

